"""Healthcare policy version comparison utilities.

This module compares two versions of healthcare content using LangChain
``Document`` objects or structured summaries produced by
``modules.summarizer.HealthcareSummarizer``. It does not read PDFs directly.

Example:
    ```python
    loader = PDFLoader()

    old_docs = loader.load_pdf("policy_2025.pdf")
    new_docs = loader.load_pdf("policy_2026.pdf")

    summarizer = HealthcareSummarizer()

    old_summary = summarizer.summarize_documents(old_docs)
    new_summary = summarizer.summarize_documents(new_docs)

    comparator = PolicyVersionComparator()

    report = comparator.compare_summaries(old_summary, new_summary)

    print(report)
    ```
"""

from __future__ import annotations

import difflib
import html
import json
import logging
import re
import time
from pathlib import Path
from typing import Any, Protocol

from langchain_core.documents import Document
from langchain_core.messages import HumanMessage, SystemMessage


class ChatModel(Protocol):
    """Protocol for LangChain-compatible chat models."""

    def invoke(self, messages: list[SystemMessage | HumanMessage]) -> Any:
        """Invoke a chat model.

        Args:
            messages: Prompt messages sent to the model.

        Returns:
            A LangChain response or response-like object.
        """
        ...


class PolicyVersionComparator:
    """Compares healthcare document versions and generates change reports."""

    def __init__(
        self,
        llm: ChatModel | None = None,
        model_name: str = "gpt-4o",
        temperature: float = 0.0,
        request_timeout: float = 60.0,
        max_retries: int = 1,
        logger: logging.Logger | None = None,
    ) -> None:
        """Initialize the policy version comparator.

        Args:
            llm: Optional LangChain-compatible chat model for semantic change
                explanation. When omitted, the comparator uses deterministic
                local comparison only until an LLM is created lazily.
            model_name: OpenAI model name for lazy LLM construction.
            temperature: Model temperature for deterministic explanations.
            request_timeout: Request timeout in seconds for OpenAI calls.
            max_retries: Number of retries for failed LLM calls.
            logger: Optional logger instance.

        Returns:
            None.

        Raises:
            ValueError: If ``max_retries`` is negative.
        """
        if max_retries < 0:
            raise ValueError("max_retries must be greater than or equal to 0.")

        self.llm = llm
        self.model_name = model_name
        self.temperature = temperature
        self.request_timeout = request_timeout
        self.max_retries = max_retries
        self.logger = logger or logging.getLogger(__name__)
        self._last_processing_time_seconds = 0.0

    def compare_documents(
        self,
        old_document: Document | list[Document],
        new_document: Document | list[Document],
    ) -> dict[str, Any]:
        """Compare two LangChain documents or two lists of documents.

        Args:
            old_document: Previous version as a LangChain ``Document`` or list
                of documents.
            new_document: New version as a LangChain ``Document`` or list of
                documents.

        Returns:
            Structured change report.

        Raises:
            TypeError: If inputs are not LangChain documents or document lists.
        """
        self.logger.info("Comparison started for LangChain documents.")
        start_time = time.perf_counter()

        old_documents = self._coerce_documents(old_document, "old_document")
        new_documents = self._coerce_documents(new_document, "new_document")
        old_text = self._documents_to_text(old_documents)
        new_text = self._documents_to_text(new_documents)
        report = self.generate_change_report(old_text, new_text)

        report["document_name"] = self._select_document_name(new_documents, old_documents)
        report["version_old"] = self._select_version(old_documents)
        report["version_new"] = self._select_version(new_documents)
        report["critical_changes"] = self.identify_critical_changes(report)

        self._last_processing_time_seconds = time.perf_counter() - start_time
        self.logger.info(
            "Comparison completed in %.2f seconds.",
            self._last_processing_time_seconds,
        )
        return report

    def compare_summaries(
        self,
        old_summary: dict[str, Any] | list[dict[str, Any]],
        new_summary: dict[str, Any] | list[dict[str, Any]],
    ) -> dict[str, Any]:
        """Compare structured summaries generated by the summarizer.

        Args:
            old_summary: Previous structured summary or summarizer result list.
            new_summary: New structured summary or summarizer result list.

        Returns:
            Structured comparison report based on summary differences.

        Raises:
            TypeError: If summary input is invalid.
        """
        self.logger.info("Comparison started for structured summaries.")
        start_time = time.perf_counter()

        old_payload = self._extract_summary_payload(old_summary, "old_summary")
        new_payload = self._extract_summary_payload(new_summary, "new_summary")
        old_text = self._summary_to_text(old_payload)
        new_text = self._summary_to_text(new_payload)
        report = self.generate_change_report(old_text, new_text)

        report["document_name"] = self._summary_document_name(new_summary)
        report["version_old"] = str(old_payload.get("version", ""))
        report["version_new"] = str(new_payload.get("version", ""))
        report["summary_differences"] = self._compare_summary_fields(
            old_payload,
            new_payload,
        )
        report["critical_changes"] = self.identify_critical_changes(report)

        self._last_processing_time_seconds = time.perf_counter() - start_time
        self.logger.info(
            "Summary comparison completed in %.2f seconds.",
            self._last_processing_time_seconds,
        )
        return report

    def generate_change_report(self, old_text: str, new_text: str) -> dict[str, Any]:
        """Generate a structured change report from old and new text.

        Args:
            old_text: Text from the previous document version.
            new_text: Text from the new document version.

        Returns:
            Structured JSON-compatible change report.

        Raises:
            TypeError: If either input is not text.
        """
        if not isinstance(old_text, str) or not isinstance(new_text, str):
            raise TypeError("old_text and new_text must be strings.")

        if not old_text.strip() and not new_text.strip():
            self.logger.warning("Both document versions are empty.")
            return self._empty_report()

        added_lines, removed_lines = self._line_level_diff(old_text, new_text)
        modified_sections = self._modified_sections(removed_lines, added_lines)
        report = self._empty_report()
        report.update(
            {
                "added_sections": added_lines,
                "removed_sections": removed_lines,
                "modified_sections": modified_sections,
                "clinical_changes": self._filter_by_category(
                    modified_sections + added_lines + removed_lines,
                    "clinical",
                ),
                "billing_changes": self._filter_by_category(
                    modified_sections + added_lines + removed_lines,
                    "billing",
                ),
                "coding_changes": self._filter_by_category(
                    modified_sections + added_lines + removed_lines,
                    "coding",
                ),
                "contract_changes": self._filter_by_category(
                    modified_sections + added_lines + removed_lines,
                    "contract",
                ),
                "medical_necessity_changes": self._filter_by_category(
                    modified_sections + added_lines + removed_lines,
                    "medical_necessity",
                ),
                "prior_authorization_changes": self._filter_by_category(
                    modified_sections + added_lines + removed_lines,
                    "prior_authorization",
                ),
            }
        )
        report["overall_summary"] = self._generate_overall_summary(report)
        return report

    def identify_critical_changes(self, change_report: dict[str, Any]) -> list[dict[str, str]]:
        """Identify high-impact reimbursement and policy changes.

        Args:
            change_report: Structured report produced by this comparator.

        Returns:
            List of critical or high-severity change records.

        Raises:
            TypeError: If ``change_report`` is not a dictionary.
        """
        if not isinstance(change_report, dict):
            raise TypeError("change_report must be a dictionary.")

        critical_changes: list[dict[str, str]] = []
        modified_sections = change_report.get("modified_sections", [])

        for section in modified_sections:
            old_text = str(section.get("old", ""))
            new_text = str(section.get("new", ""))
            prior_auth_change = self._detect_prior_authorization_change(old_text, new_text)
            if prior_auth_change:
                critical_changes.append(prior_auth_change)

            threshold_change = self._detect_threshold_change(old_text, new_text)
            if threshold_change:
                critical_changes.append(threshold_change)

        for field_name in (
            "billing_changes",
            "coding_changes",
            "contract_changes",
            "medical_necessity_changes",
            "prior_authorization_changes",
        ):
            for value in change_report.get(field_name, []):
                text_value = str(value)
                keyword_change = self._detect_keyword_critical_change(field_name, text_value)
                if keyword_change:
                    critical_changes.append(keyword_change)

        deduplicated_changes = self._deduplicate_changes(critical_changes)
        if deduplicated_changes:
            self.logger.warning("Critical changes detected: %s", len(deduplicated_changes))
        return deduplicated_changes

    def export_change_report(self, report: dict[str, Any], output_path: str | Path) -> None:
        """Export a change report as JSON, Markdown, or HTML.

        Args:
            report: Structured change report.
            output_path: Destination path. ``.md`` writes Markdown, ``.html``
                writes HTML, and all other extensions write JSON.

        Returns:
            None.

        Raises:
            TypeError: If ``report`` is not a dictionary.
            OSError: If the output path cannot be written.
        """
        if not isinstance(report, dict):
            raise TypeError("report must be a dictionary.")

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        suffix = path.suffix.lower()

        if suffix == ".md":
            path.write_text(self._to_markdown(report), encoding="utf-8")
        elif suffix == ".html":
            path.write_text(self._to_html(report), encoding="utf-8")
        else:
            path.write_text(json.dumps(report, indent=2), encoding="utf-8")

        self.logger.info("Change report exported: %s", path)

    def get_change_statistics(self, report: dict[str, Any]) -> dict[str, int | str]:
        """Calculate change statistics from a comparison report.

        Args:
            report: Structured change report.

        Returns:
            Statistics dictionary with added, removed, modified, critical, and
            processing time values.

        Raises:
            TypeError: If ``report`` is not a dictionary.
        """
        if not isinstance(report, dict):
            raise TypeError("report must be a dictionary.")

        return {
            "added": len(report.get("added_sections", [])),
            "removed": len(report.get("removed_sections", [])),
            "modified": len(report.get("modified_sections", [])),
            "critical": len(report.get("critical_changes", [])),
            "processing_time": f"{self._last_processing_time_seconds:.2f}s",
        }

    def _empty_report(self) -> dict[str, Any]:
        """Create an empty report using the required schema.

        Args:
            None.

        Returns:
            Empty structured change report.
        """
        return {
            "document_name": "",
            "version_old": "",
            "version_new": "",
            "added_sections": [],
            "removed_sections": [],
            "modified_sections": [],
            "clinical_changes": [],
            "billing_changes": [],
            "coding_changes": [],
            "contract_changes": [],
            "medical_necessity_changes": [],
            "prior_authorization_changes": [],
            "overall_summary": "",
        }

    def _coerce_documents(
        self,
        value: Document | list[Document],
        parameter_name: str,
    ) -> list[Document]:
        """Coerce a document input into a document list.

        Args:
            value: LangChain document or list of documents.
            parameter_name: Name used in validation errors.

        Returns:
            List of LangChain documents.

        Raises:
            TypeError: If the value is not a valid document input.
        """
        if isinstance(value, Document):
            return [value]
        if isinstance(value, list) and all(isinstance(item, Document) for item in value):
            return value
        raise TypeError(f"{parameter_name} must be a Document or list of Documents.")

    def _documents_to_text(self, documents: list[Document]) -> str:
        """Concatenate document text.

        Args:
            documents: LangChain documents.

        Returns:
            Combined document text.
        """
        return "\n".join(document.page_content or "" for document in documents)

    def _line_level_diff(self, old_text: str, new_text: str) -> tuple[list[str], list[str]]:
        """Generate line-level additions and removals.

        Args:
            old_text: Previous document text.
            new_text: New document text.

        Returns:
            Tuple of added lines and removed lines.
        """
        old_lines = self._normalize_lines(old_text)
        new_lines = self._normalize_lines(new_text)
        diff = difflib.ndiff(old_lines, new_lines)
        added: list[str] = []
        removed: list[str] = []

        for line in diff:
            if line.startswith("+ "):
                added.append(line[2:])
            elif line.startswith("- "):
                removed.append(line[2:])

        return added, removed

    def _normalize_lines(self, text: str) -> list[str]:
        """Normalize text into comparable non-empty lines.

        Args:
            text: Raw text to normalize.

        Returns:
            List of stripped non-empty lines.
        """
        return [line.strip() for line in text.splitlines() if line.strip()]

    def _modified_sections(
        self,
        removed_lines: list[str],
        added_lines: list[str],
    ) -> list[dict[str, Any]]:
        """Pair similar removed and added lines as modified sections.

        Args:
            removed_lines: Removed text lines.
            added_lines: Added text lines.

        Returns:
            List of modification records containing old text, new text, and
            similarity ratio.
        """
        modified: list[dict[str, Any]] = []
        unmatched_added = added_lines.copy()

        for removed in removed_lines:
            best_match = self._best_match(removed, unmatched_added)
            if not best_match:
                continue

            added, score = best_match
            if score >= 0.45:
                modified.append(
                    {
                        "old": removed,
                        "new": added,
                        "similarity": round(score, 3),
                        "meaning": self._explain_change(removed, added),
                    }
                )
                unmatched_added.remove(added)

        return modified

    def _best_match(self, removed: str, added_lines: list[str]) -> tuple[str, float] | None:
        """Find the most similar added line for a removed line.

        Args:
            removed: Removed line.
            added_lines: Candidate added lines.

        Returns:
            Best matching line and similarity score, or ``None``.
        """
        if not added_lines:
            return None

        scored = [
            (added, difflib.SequenceMatcher(None, removed.lower(), added.lower()).ratio())
            for added in added_lines
        ]
        return max(scored, key=lambda item: item[1])

    def _filter_by_category(self, changes: list[Any], category: str) -> list[Any]:
        """Filter changes by healthcare category keywords.

        Args:
            changes: Text changes or modification dictionaries.
            category: Internal category name.

        Returns:
            Changes matching category keywords.
        """
        keywords = self._category_keywords().get(category, ())
        matches: list[Any] = []
        for change in changes:
            text = self._change_to_text(change).lower()
            if any(keyword in text for keyword in keywords):
                matches.append(change)
        return matches

    def _category_keywords(self) -> dict[str, tuple[str, ...]]:
        """Return healthcare change category keywords.

        Args:
            None.

        Returns:
            Mapping of category names to keyword tuples.
        """
        return {
            "clinical": (
                "diagnosis",
                "treatment",
                "therapy",
                "clinical",
                "guideline",
                "symptom",
                "condition",
            ),
            "billing": (
                "billing",
                "payment",
                "reimbursement",
                "allowed amount",
                "deny",
                "denial",
                "claim",
            ),
            "coding": (
                "cpt",
                "hcpcs",
                "icd",
                "modifier",
                "code",
                "coding",
            ),
            "contract": (
                "contract",
                "provider",
                "payer",
                "fee schedule",
                "term",
                "rate",
            ),
            "medical_necessity": (
                "medical necessity",
                "medically necessary",
                "criteria",
                "weeks",
                "months",
                "required documentation",
            ),
            "prior_authorization": (
                "prior authorization",
                "preauthorization",
                "pre-authorization",
                "authorization required",
                "not required",
            ),
        }

    def _change_to_text(self, change: Any) -> str:
        """Convert a change object to searchable text.

        Args:
            change: String or structured change object.

        Returns:
            Searchable text representation.
        """
        if isinstance(change, dict):
            return " ".join(str(value) for value in change.values())
        return str(change)

    def _generate_overall_summary(self, report: dict[str, Any]) -> str:
        """Generate a human-readable overall change summary.

        Args:
            report: Structured deterministic change report.

        Returns:
            Overall change summary.
        """
        llm_summary = self._try_llm_summary(report)
        if llm_summary:
            return llm_summary

        added = len(report.get("added_sections", []))
        removed = len(report.get("removed_sections", []))
        modified = len(report.get("modified_sections", []))
        if added == 0 and removed == 0 and modified == 0:
            return "No meaningful content changes were detected."
        return (
            f"Detected {added} added sections, {removed} removed sections, "
            f"and {modified} modified sections. Review categorized changes "
            "for clinical, reimbursement, coding, contract, medical necessity, "
            "and prior authorization impact."
        )

    def _try_llm_summary(self, report: dict[str, Any]) -> str:
        """Attempt to generate a semantic summary with an LLM.

        Args:
            report: Structured deterministic change report.

        Returns:
            LLM-generated summary text, or an empty string on failure.
        """
        llm = self._get_llm()
        if llm is None:
            return ""

        system_prompt = (
            "You are a healthcare policy analyst. Compare two healthcare "
            "policy versions. Identify only meaningful policy changes. Ignore "
            "formatting differences. Highlight reimbursement, coding, "
            "contract, and clinical changes. Return structured JSON."
        )
        human_prompt = (
            "Summarize the business meaning of this deterministic change "
            "report in one concise paragraph. Return JSON with one key named "
            f"overall_summary.\n\n{json.dumps(report)}"
        )
        messages = [SystemMessage(content=system_prompt), HumanMessage(content=human_prompt)]

        for attempt in range(1, self.max_retries + 2):
            try:
                self.logger.info("Submitting change summary API request. Attempt: %s", attempt)
                response = llm.invoke(messages)
                content = self._extract_response_content(response)
                parsed = json.loads(self._strip_code_fences(content))
                if isinstance(parsed, dict):
                    return str(parsed.get("overall_summary", ""))
            except (json.JSONDecodeError, RuntimeError, TimeoutError, ValueError) as error:
                self.logger.error("Change summary API request failed: %s", error)
        return ""

    def _get_llm(self) -> ChatModel | None:
        """Return the configured LLM, creating ChatOpenAI lazily when possible.

        Args:
            None.

        Returns:
            LangChain-compatible chat model or ``None``.
        """
        if self.llm is not None:
            return self.llm

        try:
            from langchain_openai import ChatOpenAI
        except ImportError:
            self.logger.warning("langchain_openai is unavailable; using local summary only.")
            return None

        try:
            self.llm = ChatOpenAI(
                model=self.model_name,
                temperature=self.temperature,
                timeout=self.request_timeout,
            )
            return self.llm
        except Exception as error:
            self.logger.error("Unable to initialize ChatOpenAI: %s", error)
            return None

    def _explain_change(self, old_text: str, new_text: str) -> str:
        """Explain a paired content modification.

        Args:
            old_text: Previous text.
            new_text: New text.

        Returns:
            Short deterministic explanation.
        """
        prior_auth = self._detect_prior_authorization_change(old_text, new_text)
        if prior_auth:
            return prior_auth["business_impact"]

        threshold = self._detect_threshold_change(old_text, new_text)
        if threshold:
            return threshold["business_impact"]

        return "Content wording changed and may require policy analyst review."

    def _detect_prior_authorization_change(
        self,
        old_text: str,
        new_text: str,
    ) -> dict[str, str] | None:
        """Detect prior authorization requirement changes.

        Args:
            old_text: Previous text.
            new_text: New text.

        Returns:
            Critical change dictionary or ``None``.
        """
        old_lower = old_text.lower()
        new_lower = new_text.lower()
        if (
            "prior authorization" in old_lower
            and "not required" in old_lower
            and "prior authorization" in new_lower
            and "required" in new_lower
            and "not required" not in new_lower
        ):
            return {
                "severity": "Critical",
                "category": "Prior Authorization",
                "old": old_text,
                "new": new_text,
                "business_impact": (
                    "Prior authorization became required, which may increase "
                    "administrative burden and affect claim approval workflows."
                ),
            }
        return None

    def _detect_threshold_change(
        self,
        old_text: str,
        new_text: str,
    ) -> dict[str, str] | None:
        """Detect medical necessity threshold changes.

        Args:
            old_text: Previous text.
            new_text: New text.

        Returns:
            High-severity change dictionary or ``None``.
        """
        old_threshold = self._extract_duration_threshold(old_text)
        new_threshold = self._extract_duration_threshold(new_text)
        if not old_threshold or not new_threshold or old_threshold == new_threshold:
            return None

        old_value, old_unit = old_threshold
        new_value, new_unit = new_threshold
        if old_unit != new_unit:
            return {
                "severity": "High",
                "category": "Medical Necessity",
                "old": f"{old_value} {old_unit}",
                "new": f"{new_value} {new_unit}",
                "business_impact": "Medical necessity timing criteria changed.",
            }

        if new_value < old_value:
            impact = "Coverage expanded because the waiting period became less restrictive."
        else:
            impact = "Coverage narrowed because the waiting period became more restrictive."

        return {
            "severity": "High",
            "category": "Medical Necessity",
            "old": f"{old_value} {old_unit}",
            "new": f"{new_value} {new_unit}",
            "business_impact": impact,
        }

    def _extract_duration_threshold(self, text: str) -> tuple[int, str] | None:
        """Extract a simple duration threshold from policy text.

        Args:
            text: Text that may contain a duration.

        Returns:
            Numeric duration and normalized unit, or ``None``.
        """
        match = re.search(r"\b(\d+)\s+(week|weeks|month|months|day|days)\b", text.lower())
        if not match:
            return None
        value = int(match.group(1))
        unit = match.group(2)
        if unit.endswith("s"):
            unit = unit[:-1]
        return value, unit

    def _detect_keyword_critical_change(
        self,
        field_name: str,
        text: str,
    ) -> dict[str, str] | None:
        """Detect critical changes from category-specific keywords.

        Args:
            field_name: Report field where the change was found.
            text: Change text.

        Returns:
            Critical change dictionary or ``None``.
        """
        lowered = text.lower()
        if field_name == "coding_changes" and any(code in lowered for code in ("cpt", "hcpcs", "icd", "modifier")):
            return {
                "severity": "High",
                "category": "Coding",
                "old": "",
                "new": text,
                "business_impact": "Coding requirements changed and may affect claim adjudication.",
            }
        if field_name == "contract_changes" and any(term in lowered for term in ("rate", "fee schedule", "payment")):
            return {
                "severity": "High",
                "category": "Contract",
                "old": "",
                "new": text,
                "business_impact": "Contract payment terms changed and may affect reimbursement.",
            }
        return None

    def _deduplicate_changes(self, changes: list[dict[str, str]]) -> list[dict[str, str]]:
        """Deduplicate critical change records.

        Args:
            changes: Critical change records.

        Returns:
            Deduplicated critical change records.
        """
        seen: set[tuple[str, str, str, str]] = set()
        deduplicated: list[dict[str, str]] = []
        for change in changes:
            key = (
                change.get("severity", ""),
                change.get("category", ""),
                change.get("old", ""),
                change.get("new", ""),
            )
            if key not in seen:
                seen.add(key)
                deduplicated.append(change)
        return deduplicated

    def _extract_summary_payload(
        self,
        summary: dict[str, Any] | list[dict[str, Any]],
        parameter_name: str,
    ) -> dict[str, Any]:
        """Extract a summarizer payload from supported summary shapes.

        Args:
            summary: Summary dictionary or summarizer result list.
            parameter_name: Name used in validation errors.

        Returns:
            Structured summary dictionary.

        Raises:
            TypeError: If input shape is unsupported.
        """
        if isinstance(summary, list):
            if not summary:
                return {}
            first_item = summary[0]
            if isinstance(first_item, dict):
                payload = first_item.get("summary", first_item)
                if isinstance(payload, dict):
                    return payload
            raise TypeError(f"{parameter_name} must contain summary dictionaries.")

        if isinstance(summary, dict):
            payload = summary.get("summary", summary)
            if isinstance(payload, dict):
                return payload

        raise TypeError(f"{parameter_name} must be a summary dictionary or list.")

    def _summary_document_name(self, summary: dict[str, Any] | list[dict[str, Any]]) -> str:
        """Extract a display document name from summary input.

        Args:
            summary: Summary dictionary or summarizer result list.

        Returns:
            Document name when available.
        """
        if isinstance(summary, list) and summary and isinstance(summary[0], dict):
            return str(summary[0].get("document", ""))
        if isinstance(summary, dict):
            return str(summary.get("document", ""))
        return ""

    def _summary_to_text(self, summary: dict[str, Any]) -> str:
        """Convert a structured summary into comparable text.

        Args:
            summary: Structured summary dictionary.

        Returns:
            Multiline text representation of summary values.
        """
        lines: list[str] = []
        for key in sorted(summary.keys()):
            value = summary[key]
            if isinstance(value, list):
                value_text = "; ".join(str(item) for item in value)
            else:
                value_text = str(value)
            lines.append(f"{key}: {value_text}")
        return "\n".join(lines)

    def _compare_summary_fields(
        self,
        old_summary: dict[str, Any],
        new_summary: dict[str, Any],
    ) -> list[dict[str, Any]]:
        """Compare summary fields exactly.

        Args:
            old_summary: Previous structured summary.
            new_summary: New structured summary.

        Returns:
            List of changed summary fields.
        """
        differences: list[dict[str, Any]] = []
        for key in sorted(set(old_summary) | set(new_summary)):
            old_value = old_summary.get(key)
            new_value = new_summary.get(key)
            if old_value != new_value:
                differences.append({"field": key, "old": old_value, "new": new_value})
        return differences

    def _select_document_name(
        self,
        preferred_documents: list[Document],
        fallback_documents: list[Document],
    ) -> str:
        """Select a document display name from metadata.

        Args:
            preferred_documents: Documents preferred for naming.
            fallback_documents: Fallback documents for naming.

        Returns:
            Document name when available.
        """
        for document in preferred_documents + fallback_documents:
            filename = document.metadata.get("filename")
            if filename:
                return str(filename)
            source = document.metadata.get("source")
            if source:
                return Path(str(source)).name
        return ""

    def _select_version(self, documents: list[Document]) -> str:
        """Select a version label from document metadata.

        Args:
            documents: LangChain documents.

        Returns:
            Version label when available.
        """
        for document in documents:
            for key in ("version", "effective_date", "date"):
                value = document.metadata.get(key)
                if value:
                    return str(value)
        return ""

    def _extract_response_content(self, response: Any) -> str:
        """Extract text content from a LangChain response.

        Args:
            response: LangChain response or response-like object.

        Returns:
            Text content.

        Raises:
            ValueError: If no text content is available.
        """
        content = getattr(response, "content", response)
        if isinstance(content, list):
            content = " ".join(str(item) for item in content)
        if not isinstance(content, str) or not content.strip():
            raise ValueError("LLM response did not contain text content.")
        return content.strip()

    def _strip_code_fences(self, content: str) -> str:
        """Remove Markdown code fences from model output.

        Args:
            content: Raw model response content.

        Returns:
            Content without wrapping Markdown code fences.
        """
        stripped = content.strip()
        if stripped.startswith("```"):
            lines = stripped.splitlines()
            if lines and lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            return "\n".join(lines).strip()
        return stripped

    def _to_markdown(self, report: dict[str, Any]) -> str:
        """Convert a change report to Markdown.

        Args:
            report: Structured change report.

        Returns:
            Markdown report text.
        """
        lines = ["# Healthcare Policy Change Report", ""]
        for key, value in report.items():
            title = key.replace("_", " ").title()
            lines.extend([f"## {title}", ""])
            if isinstance(value, list):
                if value:
                    for item in value:
                        lines.append(f"- {item}")
                else:
                    lines.append("- None")
            else:
                lines.append(str(value) if value else "Not specified")
            lines.append("")
        return "\n".join(lines).strip() + "\n"

    def _to_html(self, report: dict[str, Any]) -> str:
        """Convert a change report to simple HTML.

        Args:
            report: Structured change report.

        Returns:
            HTML report text.
        """
        body = ["<html><body>", "<h1>Healthcare Policy Change Report</h1>"]
        for key, value in report.items():
            title = html.escape(key.replace("_", " ").title())
            body.append(f"<h2>{title}</h2>")
            if isinstance(value, list):
                body.append("<ul>")
                if value:
                    for item in value:
                        body.append(f"<li>{html.escape(str(item))}</li>")
                else:
                    body.append("<li>None</li>")
                body.append("</ul>")
            else:
                body.append(f"<p>{html.escape(str(value) if value else 'Not specified')}</p>")
        body.append("</body></html>")
        return "\n".join(body)

